---
title: "Gene Scores and Marker Genes"
---

### Gene Activity Scores

While ArchR is able to robustly call clusters, it is not possible to know _a priori_ which cell type is represented by each cluster. This task is often left to manual annotation because every application is different.

To do this cell type annotation, we use prior knowledge of cell type-specific marker genes and we estimate _gene activity scores_ for these genes. A gene activity score is essentially a prediction of how highly expressed a gene will be based on the accessibility of regulatory elements in the vicinity of the gene promoter.

Specifically, the 200-kb region centered on the given TSS is tiled into 1000-bp bins and the insertions per bin are counted. Each of these bins is then weighted proportional to the distance from the TSS because regulatory elements closer to the promoter are more likely to affect the promoter.

[INSERT DRAWING OF GENE ACTIVITY SCORE GENERATION]

These gene activity scores are calculated for each `ArrowFile` at the time of creation if the parameter `addGeneScoreMat` is set to `TRUE` (the default) or at any time by using the `addGeneScoreMatrix()` function. Once caluclated, individual cells of a UMAP projection can be colored by their gene activity scores to help with the identification of various cell types. For example, in the plot below from the tutorial, __QQQ__ cells are highlighted based on their gene activity scores for __QQQ__.

[INSERT UMAP GENE SCORE PLOT FROM PBMCs]

It is important to note that not all genes behave well with gene activity scores. In particular, genes that reside in very gene-dense areas can be problematic because the promoter accessibility of nearby genes contribute to their score and it is also not necessarily true that nearby regulatory elements will affect their expression. Thus, it is always best to sanity check all gene activity score analyses.

### Marker Genes

An alternative less-supervised method for identification of cell types is the identification of features that are highly specific to the given cluster (or a small group of clusters). Here, a feature could be a single regulatory element or it could be a gene. ArchR does this using the `markerFeatures()` function which can take as input any matrix via the `useMatrix` parameter and it identifies features unique to the groups indicated by the `groupBy` parameter (default is "Clusters"). If the `useMatrix` parameter is set to "GeneScoreMatrix", then the function will identify the genes that appear to be uniquely active in each cell type. This provides an unbiased way of seeing which genes are predicted to be active in each cluster and can aid in cluster annotation.

__Can you not set the max number of clusters that can have the activity??__

It is worth noting that the same function can be used with the `useMatrix` parameter set to "TileMatrix" or __QQQ__ in order to identify genomic regions or regulatory elements that are highly specific to a certain cluster.