# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowCorCpp <- function(idxX, idxY, X, Y) {
    .Call('_ArchR_rowCorCpp', PACKAGE = 'ArchR', idxX, idxY, X, Y)
}

rleSumsStrandedChr <- function(rle, x, strand, width) {
    .Call('_ArchR_rleSumsStrandedChr', PACKAGE = 'ArchR', rle, x, strand, width)
}

rleSumsStranded <- function(rleList, grList, width, as_integer) {
    .Call('_ArchR_rleSumsStranded', PACKAGE = 'ArchR', rleList, grList, width, as_integer)
}

tabulate2dCpp <- function(x, xmin, xmax, y, ymin, ymax) {
    .Call('_ArchR_tabulate2dCpp', PACKAGE = 'ArchR', x, xmin, xmax, y, ymin, ymax)
}

computeSparseRowVariances <- function(j, val, rm, n) {
    .Call('_ArchR_computeSparseRowVariances', PACKAGE = 'ArchR', j, val, rm, n)
}

determineOverlapCpp <- function(m, overlapCut) {
    .Call('_ArchR_determineOverlapCpp', PACKAGE = 'ArchR', m, overlapCut)
}

kmerIdxCpp <- function(str, window, n, kmer) {
    .Call('_ArchR_kmerIdxCpp', PACKAGE = 'ArchR', str, window, n, kmer)
}

kmerPositionFrequencyCpp <- function(string_vector, strand_vector, window, w, kmer) {
    .Call('_ArchR_kmerPositionFrequencyCpp', PACKAGE = 'ArchR', string_vector, strand_vector, window, w, kmer)
}

kmerIDFrequencyCpp <- function(string_vector, id_vector, n_id, window, w, kmer) {
    .Call('_ArchR_kmerIDFrequencyCpp', PACKAGE = 'ArchR', string_vector, id_vector, n_id, window, w, kmer)
}

